apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-server
  labels:
    app: simple-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-server
  template:
    metadata:
      labels:
        app: simple-web-server
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: simple-web-server
          image: public.ecr.aws/r7m7o9d4/flask-app-mar22:0.0.2
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-server-service
spec:
  selector:
    app: simple-web-server
  ports:
    - port: 8080
      targetPort: 8080
